FROM node:20-alpine

WORKDIR /app

# Copie des fichiers de dépendances
COPY /src/client/package*.json ./
# Installation des dépendances => mettre ci plutard (npm ci)
RUN npm install 


# Copie du code source
COPY /src/client .

# Exposition du port Vite par défaut
EXPOSE 5173

# Commande de développement avec hot reload
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]